<?php

/**
 * @file
 * Contains spotify_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function spotify_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spotify_api module.
    case 'help.page.spotify_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the spotify api connection module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function spotify_api_theme($existing, $type, $theme, $path) {
  return [
    'spotify_api' => [
      'variables' => [
        'id' => NULL,
      ],
    ],
    'spotify_container' => [
      'variables' => [
        'results' => NULL,
        'title' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function spotify_api_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'spotify_api/spotify_api_js';
}